AWSTemplateFormatVersion: '2010-09-09'
Description: 'Crypto Market Data POC: S3, IAM, and Glue Catalog'

Parameters:
  BucketName:
    Type: String
    Default: crypto-market-data-lake-poc-2026
  CodeHashParam:
    Type: String
    Default: "initial"

Resources:
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: crypto_market_db

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3DataLakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "${DataLakeBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt DataLakeBucket.Arn

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: crypto_market_crawler
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub "s3://${DataLakeBucket}/trades/"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DEPRECATE_IN_DATABASE"
  
  FirehoseMarketCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: firehose_market_crawler
      Role: !GetAtt GlueCrawlerRole.Arn 
      DatabaseName: !Ref GlueDatabase
      TablePrefix: firehose_
      Targets:
        S3Targets:
          - Path: !Sub "s3://${DataLakeBucket}/bronze/trades/"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DEPRECATE_IN_DATABASE"

  BronzeToSilverEtlJob:
    Type: AWS::Glue::Job
    Properties:
      Name: crypto_bronze_to_silver_etl
      Role: !GetAtt GlueCrawlerRole.Arn 
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 60
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${DataLakeBucket}/scripts/bronze_to_silver_etl.py"
        PythonVersion: "3"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        "--S3_SILVER_PATH": !Sub "s3://${DataLakeBucket}/silver/trades/"
        "--GLUE_DB_NAME": "crypto_market_db" # Passing the DB name
        "--GLUE_TABLE_NAME": "trades"        # Passing the Table name
        "--CODE_HASH": !Ref CodeHashParam  # We will pass this in via CLI

  FirehoseBronzeToSilverJob:
    Type: AWS::Glue::Job
    Properties:
      Name: firehose_bronze_to_silver_etl
      Role: !GetAtt GlueCrawlerRole.Arn 
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 60
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${DataLakeBucket}/scripts/firehose_bronze_to_silver_etl.py"
        PythonVersion: "3"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        "--S3_SILVER_PATH": !Sub "s3://${DataLakeBucket}/silver/firehose_trades/"
        "--GLUE_DB_NAME": "crypto_market_db" # Passing the DB name
        "--GLUE_TABLE_NAME": "firehose_trades"        # Passing the Table name
        "--CODE_HASH": !Ref CodeHashParam  # We will pass this in via CLI
        "--enable-metrics": "true"
        "--datalake-formats": "iceberg"
        "--conf": "spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.glue_catalog.warehouse=s3://crypto-market-data-lake-poc-2026/silver/ --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
  
  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !GetAtt DataLakeBucket.Arn
                  - !Sub "${DataLakeBucket.Arn}/*"

  MarketDataFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: crypto-market-firehose
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt DataLakeBucket.Arn
        RoleARN: !GetAtt FirehoseDeliveryRole.Arn
        # Matches your PySpark / Athena partition structure
        Prefix: "bronze/trades/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
        ErrorOutputPrefix: "bronze/errors/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}/"
        BufferingHints:
          SizeInMBs: 1
          IntervalInSeconds: 60